# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title: Hyde 2.0
tagline: 'A Jekyll theme'
description: 'The updated version of Hyde them'
url: http://hyde.getpoole.com
baseurl: ""

author:
  name: 'Ching Ching'
  url: https://chingchinglee.com

paginate: 12

# Custom vars
version: 3.8.5

# Uncomment the repo line to run GitHub Page
# github:
#   repo:           https://github.com/poole/hyde

# Plugin
plugins:
- jekyll-paginate
- jekyll-sitemap

exclude:
- Gemfile
- Gemfile.lock
- package.json
- node_modules
- gulpfile.js
- README.md
